# Generated by Django 5.1.6 on 2025-02-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='tablet_count',
            new_name='tabletCount',
        ),
    ]
